server:
  applicationConnectors:
    - type: http
      port: 8001
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: umar1234
  url: jdbc:postgresql://localhost:5432/EmployeeManagement